config/routes.rb
Discover::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :feeds
  resources :profiles

  root :to => "feeds#index"

  get "posts/new"

  get "signup" => 'users#new'

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates :body
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_one :profile
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, :email, :fname, :lname, presence: true
  validates :username, :fname, :lname, :email, length: { maximum: 50 }
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :username, :email, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :signed_in_user
  
  def index

  end

  def show

  end

  private

  def signed_in_user
    if !logged_in?
      require_login
      redirect_to login_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
		@post = Post.new	
  end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:success] = "Post successfully create!"
		else
			flash.now[:danger] = "Post could not be created. Error: #{@user.errors.full_messages.join('. ')}"
			render 'new'
	end

	private
	def post_params
		params.require(:post).permit(:id, :body, :user_id)
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index

  end

  def create

  end

  def show

  end

  def edit

  end

  def update

  end

  def destroy

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to root_url
    end
  end

  def create
    @user = User.find_by(username: params[:session][:username].downcase)
    if @user && @user.authenticate(params[:session][:password])
      @user = login(@user) if @user
      flash[:success] = "Login Successful"
      redirect_back_or_to feeds_path
    else
      flash.now[:danger] = "Invalid Username or Password"
      render 'new'
    end
  end

  def destroy
    @current_user = nil
    session.clear
    flash[:success] = "You have been logged out"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    unless logged_in?
      @user = User.new
    else
      redirect_to root_url
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "User Successfully Created."
      redirect_to login_path
    else
      flash.now[:danger] = "Could not create user. Error: #{@user.errors.full_messages.join('. ')}"
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :fname, :lname, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def require_login
    if !logged_in?
      session[:return_to_url] = request.url if request.get?
    end
  end

  def login(user)
    @current_user = nil

    old_session = session.dup.to_hash
    old_session.each do |key, value|
      session[key.to_sym] = value
    end

    session[:user_id] = user.id
    current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def redirect_back_or_to(url)
    redirect_to(session[:return_to_url] || url)
    session[:return_to_url] = nil
  end
end

app/views/feeds/index.html.haml
%h1#coming-soon Coming Soon

app/views/layouts/_header.html.haml
%header 
  = link_to(root_url) do
    = image_tag "logo1.png", id: "logo"
    %h1#headlink iscover

- if logged_in?
  .container-main.container#navbar-container
    %nav.navbar.navbar-default{role: 'navigation'}
      %ul.nav.nav-tabs
        - home = 'active' if request.url == root_url && request.get?
        - profile_active = 'active' if request.url == profiles_url && request.get?
        %li{class: home }
          = link_to "Home", root_url
        %li{class: profile_active } 
          = link_to "Profile", profiles_path
        %li
          = link_to "Logout", logout_path

app/views/layouts/application.html.haml
!!! 5
%head  
  %title Discover
  = stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Satisfy'
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  = render 'layouts/header'
  .container
    .row
      .col-md-12
        #flash
          - if flash
            - flash.each do |key, value|
              .alert.alert-dismissable{ class: "alert-#{key}" }
                %button.close{:'data-dismiss' => 'alert', :'aria-hidden' => 'true', type: 'button'} &times;
                %p= value
        = yield

    %footer
      %p.copyright
        &copy; #{Date.today.year} Discover, All rights reserved
      %p.version
        = Discover::VERSION

app/views/posts/new.html.haml
%h1 Posts#new
%p Find me in app/views/posts/new.html.haml

app/views/profiles/index.html.haml
%h1 Coming Soon

app/views/users/new.html.haml
%h1.text-center Sign Up
.col-md-4.col-md-offset-4
  = form_for @user, html: { class: "form-horizontal well" } do  |f|
    .form-group
      = f.label :email, class: "control-label col-md-4"
      .col-md-8
        = f.email_field :email, class: "form-control" 
    .form-group
      = f.label :username, class: "control-label col-md-4"
      .col-md-8
        = f.text_field :username, class: "form-control"
    .form-group
      = f.label :fname, "First Name", class: "control-label col-md-4"
      .col-md-8
        = f.text_field :fname, class: "form-control"
    .form-group
      = f.label :lname, "Last Name", class: "control-label col-md-4"
      .col-md-8
        = f.text_field :lname, class: "form-control"
    .form-group
      = f.label :password, class: "control-label col-md-4"
      .col-md-8
        = f.password_field :password, class: "form-control" 
    .form-group
      = f.label :password_confirmation, "Password Confirmation", class: "control-label col-md-4", style: "margin-top: -8px;"
      .col-md-8
        = f.password_field :password_confirmation, class: "form-control" 

    .form-group-submit.form-group
      .col-md-4.col-md-offset-4
        = submit_tag "Sign Up", class: "btn btn-primary"